{% set name = "chromadb" %}
{% set version = "0.4.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chromadb-{{ version }}.tar.gz
  sha256: a5c80b4e4ad9b236ed2d4899a5b9e8002b489293f2881cb2cadab5b199ee1c72
  patches:
    # Once the patch is merged, we can turn on automerge again
    # https://github.com/chroma-core/chroma/pull/1639
    - 1639.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - orjson >=3.9.12
    - python-build >=1.0.3
    - mmh3 >=4.0.1
    - opentelemetry-instrumentation-fastapi >=0.41b0
    - pyyaml >=6.0.0
    - opentelemetry-api >=1.2.0
    - opentelemetry-exporter-otlp-proto-grpc >=1.2.0
    - opentelemetry-sdk >=1.2.0
    - python-kubernetes >=28.1.0
    - tenacity >=8.2.3
    - grpcio >=1.58.0
    - typer >=0.9.0
    - bcrypt >=4.0.1
    - python
    - fastapi >=0.95.2
    - graphlib-backport >=1.0.3  # [py<39]
    - chroma-hnswlib ==0.7.3
    - importlib-resources
    - numpy >=1.22.5
    - onnxruntime >=1.14.1
    - overrides >=7.3.1
    - posthog >=2.4.0
    - pulsar-client >=3.1.0
    - pydantic >=1.9
    - pypika >=0.48.9
    - requests >=2.28
    - tokenizers >=0.13.2
    - tqdm >=4.65.0
    - typing-extensions >=4.5.0
    - uvicorn >=0.18.3

test:
  imports:
    - chromadb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.trychroma.com/
  summary: "Chroma: The AI-native open-source embedding database"
  license: Apache-2.0
  license_file:
    - LICENSE
    - clients/js/LICENSE
  description: |
    Chroma is the open-source embedding database. Chroma makes it easy to build
    LLM apps by making knowledge, facts, and skills pluggable for LLMs.

    ![banner](https://docs.trychroma.com/img/hrm4.svg)

    PyPI: [https://pypi.org/project/chromadb](https://pypi.org/project/chromadb)

    ---

    :fire: The conda-forge recipe was generated with [Conda-Forger App](https://sugatoray-conda-forger.streamlit.app/).

    :point_right: [![Streamlit App](https://static.streamlit.io/badges/streamlit_badge_black_white.svg)](https://sugatoray-conda-forger.streamlit.app/)

    [_streamlit-conda-forger-app]: https://sugatoray-conda-forger.streamlit.app/

  dev_url: https://github.com/chroma-core/chroma
  doc_url: https://docs.trychroma.com/

extra:
  recipe-maintainers:
    - sugatoray
    - xhochy
    - pavelzw
