{% set name = "chromadb" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/chromadb-{{ version }}.tar.gz
    sha256: 271ed476da71f46b44d0d8e1ee63bb009e3b0d81903b973422522f5637b169f2
  - url: https://raw.githubusercontent.com/chroma-core/chroma/refs/tags/{{ version }}/LICENSE
    sha256: c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4
    fn: LICENSE

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    # Needed for protoc
    - libprotobuf
    - make
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.0,<2.0                     # [build_platform != target_platform]
  host:
    - python
    - maturin >=1.0,<2.0
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - jsonschema >=4.19.0
    - typing_extensions >=4.5.0
    - uvicorn >=0.18.3
    - rich >=10.11.0
    - httpx >=0.27.0
    - orjson >=3.9.12
    - python-build >=1.0.3
    - mmh3 >=4.0.1
    - opentelemetry-instrumentation-fastapi >=0.41b0
    - pyyaml >=6.0.0
    - opentelemetry-api >=1.2.0
    - opentelemetry-exporter-otlp-proto-grpc >=1.2.0
    - opentelemetry-sdk >=1.2.0
    - python-kubernetes >=28.1.0
    - tenacity >=8.2.3
    - grpcio >=1.58.0
    - typer >=0.9.0
    - bcrypt >=4.0.1
    - python
    - fastapi ==0.115.9
    - chroma-hnswlib ==0.7.6
    - importlib-resources
    - numpy >=1.22.5
    - onnxruntime >=1.14.1
    - overrides >=7.3.1
    - posthog >=2.4.0
    - pulsar-client >=3.1.0
    - pydantic >=1.9
    - pypika >=0.48.9
    - requests >=2.28
    - tokenizers >=0.13.2
    - tqdm >=4.65.0
    - typing-extensions >=4.5.0
    - uvicorn-standard >=0.18.3

test:
  imports:
    - chromadb
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://www.trychroma.com/
  summary: "Chroma: The AI-native open-source embedding database"
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  description: |
    Chroma is the open-source embedding database. Chroma makes it easy to build
    LLM apps by making knowledge, facts, and skills pluggable for LLMs.
  dev_url: https://github.com/chroma-core/chroma
  doc_url: https://docs.trychroma.com/

extra:
  recipe-maintainers:
    - sugatoray
    - xhochy
    - pavelzw
