{% set name = "chromadb" %}
{% set version = "0.3.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chromadb-{{ version }}.tar.gz
  sha256: ef76be756551168c05e137704270e4c7b78a6e9faa6f6b96e94bae42ee32caea

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python
    - clickhouse-connect >=0.5.7
    - python-duckdb >=0.7.1
    - fastapi >=0.85.1
    - graphlib-backport >=1.0.3  # [py<39]
    - hnswlib >=0.7
    - numpy >=1.21.6
    - onnxruntime >=1.14.1
    - overrides >=7.3.1
    - pandas >=1.3
    - posthog >=2.4.0
    - pulsar-client >=3.1.0
    - pydantic >=1.9
    - requests >=2.28
    - tokenizers >=0.13.2
    - tqdm >=4.65.0
    - typing-extensions >=4.5.0
    - uvicorn >=0.18.3

test:
  imports:
    - chromadb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.trychroma.com/
  summary: 'Chroma: The AI-native open-source embedding database'
  license: Apache-2.0
  license_file:
    - LICENSE
    - clients/js/LICENSE
  description: |
    Chroma is the open-source embedding database. Chroma makes it easy to build
    LLM apps by making knowledge, facts, and skills pluggable for LLMs.

    ![banner](https://docs.trychroma.com/img/hrm4.svg)

    PyPI: [https://pypi.org/project/chromadb](https://pypi.org/project/chromadb)

    ---

    :fire: The conda-forge recipe was generated with [Conda-Forger App](https://sugatoray-conda-forger.streamlit.app/).

    :point_right: [![Streamlit App](https://static.streamlit.io/badges/streamlit_badge_black_white.svg)](https://sugatoray-conda-forger.streamlit.app/)

    [_streamlit-conda-forger-app]: https://sugatoray-conda-forger.streamlit.app/

  dev_url: https://github.com/chroma-core/chroma
  doc_url: https://docs.trychroma.com/

extra:
  recipe-maintainers:
    - sugatoray
    - xhochy
